name: Check Upstream Updates and Build

on:
  schedule:
    - cron: '0 * * * *'  # Vérifie chaque heure si l'upstream a changé
  push:
    branches: master

jobs:
  check-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch upstream changes
        run: |
          git remote add upstream https://gitlab.com/ludo444/fireflyrevoluttransactions.git
          git fetch upstream
          git checkout master
          git merge upstream/master --no-edit || true

      - name: Check if there are new commits
        id: check_changes
        run: echo "::set-output name=changes::$(git rev-list HEAD...upstream/master --count)"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}  # Assurez-vous d'utiliser un token d'accès

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: kdtheory/revolut-importer:latest
